name: (PRODUCTION) build, vercel

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: deploy in staging
        run: npx vercel --confirm --prod -n ${{ secrets.PROJECT_ID }} -t ${{ secrets.DISCORD_FRONT_TOKEN }} --scope ${{ secrets.ORG_ID }} -e REACT_APP_API_URL=${{ secrets.API_URL_PRODUCTION }} -b REACT_APP_API_URL=${{ secrets.API_URL_PRODUCTION }}
