name: (STAGING) build, vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: deploy to Vercel
        id: branch_deploy_vercel
        run: npx vercel --confirm -n ${{ secrets.VERCEL_PROJECT_ID }} -t ${{ secrets.DISCORD_FRONT_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} -b REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
